# Generated by Django 5.2.5 on 2026-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("sales", "Sales Staff"),
                    ("warehouse", "Warehouse Staff"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
