# Generated by Django 5.2.5 on 2026-07-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("seller", "Seller")],
                default="seller",
                max_length=20,
            ),
        ),
    ]
