# Generated by Django 5.2.5 on 2026-07-22 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
