# Generated by Django 5.2.5 on 2026-07-07 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("role_title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("performance_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("sick", "Sick"),
                            ("unpaid", "Unpaid"),
                            ("other", "Other"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the payroll month.", unique=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half day"),
                            ("on_leave", "On leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("working_days", models.PositiveIntegerField(default=0)),
                (
                    "days_absent",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "absence_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_on", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="hr.employee",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hr.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__name"],
                "unique_together": {("run", "employee")},
            },
        ),
    ]
