# Generated by Django 5.1.6 on 2025-03-11 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ware_images', to='inventory.ware'),
        ),
        migrations.AddField(
            model_name='warevariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.size'),
        ),
        migrations.AddField(
            model_name='warevariant',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.ware'),
        ),
        migrations.AddField(
            model_name='batch',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.warevariant'),
        ),
        migrations.AlterUniqueTogether(
            name='warevariant',
            unique_together={('ware', 'size')},
        ),
    ]
