# Generated by Django 5.1.6 on 2025-03-12 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warevariant',
            name='stock',
        ),
        migrations.AlterField(
            model_name='ware',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warevariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='ware',
            unique_together={('user', 'name', 'brand')},
        ),
    ]
