# Generated by Django 5.2.5 on 2026-07-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_backfill_opening_movements"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
