# Generated by Django 5.2.5 on 2026-06-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_supplier_warehouse_warevariant_reorder_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warevariant",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="warevariant",
            name="wholesale_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
