# Generated by Django 5.2.5 on 2026-06-24 21:44

from django.db import migrations
from django.db.models import F


def copy_price_to_retail(apps, schema_editor):
    WareVariant = apps.get_model("inventory", "WareVariant")
    # Seed retail (and wholesale) price from the legacy single price for any
    # variant that hasn't had the new prices set yet.
    WareVariant.objects.filter(retail_price=0).update(
        retail_price=F("price"), wholesale_price=F("price")
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_warevariant_retail_price_warevariant_wholesale_price"),
    ]

    operations = [
        migrations.RunPython(copy_price_to_retail, noop),
    ]
