# Generated by Django 5.2.5 on 2026-07-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="credit_limit",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_type",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="outstanding_balance",
        ),
    ]
