# Generated by Django 5.2.5 on 2026-07-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnoteitem",
            name="sale_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credited_items",
                to="sales.saleitem",
            ),
        ),
    ]
