# Generated by Django 5.2.5 on 2026-06-24 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
