# Generated by Django 5.2.5 on 2026-07-22 19:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_offline_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
    ]
