# Generated by Django 5.2.5 on 2026-07-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_inventory_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
        ),
    ]
